---
- name: Install packages for power managent support and ipxe
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - fence-agents
    - ipxe
    - ipmitool

- name: Download Cobbler source
  get_url:
    url: "{{ cobbler_source_url }}"
    dest: "/root/{{ cobbler_source_file }}" 

- name: Extract cobbler source
  unarchive:
    src: "/root/{{ cobbler_source_file }}"
    dest: /root/
    remote_src: True

- name: Make / Install Cobbler
  shell: make && make install
  args:
    chdir: "/root/{{ cobbler_source_dir }}"
    creates: /etc/cobbler/settings  

- name: Link cobbler python code with python libs
  file:
    src:  /usr/local/lib/python2.7/dist-packages/cobbler
    dest: /usr/lib/python2.7/dist-packages/cobbler
    state: link
    force: True

- name: Set Cobbler Django app secret key
  lineinfile:
    dest: /usr/local/share/cobbler/web/settings.py
    regexp: '^SECRET_KEY'
    line: "SECRET_KEY = '{{ cobbler_secret_key }}'"

- name: Enable Apache proxy module
  apache2_module:
    state: present
    name: "{{ item }}" 
  with_items:
    - proxy
    - proxy_http

- name: Enable Cobbler Apache2 conf
  command: a2enconf "{{ item }}"
  with_items:
    - cobbler
    - cobbler_web

- name: Copy wsgi app conf
  copy:
    src: files/cobbler.wsgi
    dest: /usr/local/share/cobbler/web/cobbler.wsgi

- name: Generate htdigest password for web interface and api
  command: htdigest /etc/cobbler/users.digest "Cobbler" cobbler

- name: Remove Apache 2.2 Order allow,deny from /etc/apache2/conf-available/cobbler.conf
  lineinfile:
    path: /etc/apache2/conf-available/cobbler.conf
    regexp: "^.*Order allow,deny"
    state: absent

- name: Replace Apache 2.2 Allow from all with Require all granted
  replace:
    path: /etc/apache2/conf-available/cobbler.conf
    regexp: "^.*Allow from all"
    replace: "    Require all granted"

- name: Set dhcp server interface
  lineinfile:
    dest: /etc/default/isc-dhcp-server
    regexp: '^INTERFACES='
    line: INTERFACES="{{ cobbler_dhcp_interface }}"

- name: Dhcp server config template
  template:
    src: templates/dhcp.j2
    dest: /etc/cobbler/dhcp.template

- name: Install systemd unit for cobbler
  command: cp /etc/cobbler/cobblerd.service /etc/systemd/system/

- name: Restart apache2 service
  systemd:
    name: apache2
    state: reloaded

- name: Add proxy server if variable global_environment_variables is set
  lineinfile:
    path: /etc/cobbler/settings
    regexp: '^proxy_url_ext'
    line: "proxy_url_ext: {{ global_environment_variables.http_proxy }}"
  when: global_environment_variables is defined

- name: Add support for ipmitool
  lineinfile:
    path: /etc/cobbler/power/fence_ipmilan.template
    line: "lanplus=1"

- name: Start Cobbler service
  systemd:
    state: restarted
    daemon_reload: yes
    name: cobblerd

- name: Wait 2 secs
  pause:
    seconds: 2

- name: Pre-create tftpboot directory
  file:
    path: /tftpboot
    state: directory
    mode: 0755

- name: Copy ipxe to tftpboot
  copy:
    remote_src: yes
    src: /usr/lib/ipxe/undionly.kpxe
    dest: /tftpboot/undionly.kpxe

- name: Get Cobbler loaders
  command: cobbler get-loaders

- name: Run Initial Cobbler sync
  command: cobbler sync

- name: Check cobbler distro list
  shell: cobbler distro list | tr -d ' '
  register: cobbler_distro_list

- debug: var=ubuntu_distro_name

- name: Import Ubuntu ISO contents
  command: cobbler import --name="{{ ubuntu_distro_name }}"  --path /root/iso
  when: ubuntu_distro_name  not in cobbler_distro_list.stdout_lines

- name: Remove ISO contents
  file:
    path: /root/iso
    state: absent

- name: Update TFTPD xinetd start options
  lineinfile:
    path: /etc/cobbler/tftpd.template
    regexp: '^.*server_args'
    line: '        server_args             = -s /tftpboot'

- name: "Replace 127.0.0.1 with primary ip /etc/cobbler/settings"
  replace:
    dest: /etc/cobbler/settings
    regexp: "127.0.0.1"
    replace: "{{ ansible_eth1.ipv4.address }}"

- name: "Enable manage DHCP /etc/cobbler/settings"
  replace:
    dest: /etc/cobbler/settings
    regexp: "manage_dhcp: 0"
    replace: "manage_dhcp: 1"

- name: Enable serial console on default profile
  command: |
    cobbler profile  edit 
      --name {{ ubuntu_distro_name }} \
      --kopts="ksdevice=bootif lang console={{cobbler_tty}} locale=en_US text priority=critical netcfg/dhcp_timeout=60 netcfg/choose_interface=auto  tty0" \
      --kopts-post="console=tty0 console={{cobbler_tty}}"
  when: cobbler_tty_enabled

- name: Get sources.list file
  copy: src=files/xenial-sources.list dest=/var/www/html/

- name: Read ssh public key
  set_fact:
    cobbler_public_key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: Copy preseed files
  copy: src=files/ubuntu-server-xenial-unattended-cobbler-rpc.seed dest=/var/lib/cobbler/kickstarts/

- name: Add late preseed script
  template: src=templates/preseed_xenial_late.j2 dest=/var/lib/cobbler/scripts/preseed_xenial_late

- name: Add late preseed snippet
  template: src=templates/preseed_xenial_post_deploy.j2 dest=/var/lib/cobbler/snippets/preseed_xenial_post_deploy

- name: Add RPC Cobbler profile
  command: |
      cobbler profile add \
      --name rpc-xenial-profile \
      --kickstart {{ cobler_ubuntu_kickstart }} \
      --distro {{ ubuntu_distro_name }} \
      --kopts="ksdevice=bootif lang locale=en_US text priority=critical netcfg/choose_interface=auto" 

- name: Edit RPC Cobbler profile
  command: |
      cobbler profile edit \
      --name rpc-xenial-profile \
      --kopts="ksdevice=bootif lang console={{cobbler_tty}} locale=en_US text priority=critical netcfg/choose_interface=auto  tty0" \
      --kopts-post="console=tty0 console={{cobbler_tty}}"
  when: cobbler_tty_enabled

- name: Cobbler sync
  command: cobbler sync

- name: Restart cobbler service
  service:
    name: cobblerd
    state: restarted

- name: Restart xinetd service
  service:
    name: xinetd
    state: restarted
